[target.x86_64-pc-windows-msvc]
linker = "link.exe"

[env]

SECURE_LINK_SERVER_HOST = "rdp.4ait.ru"
SECURE_LINK_SERVER_PORT = "60200"

#SECURE_LINK_SERVICE_WITH_LOAD_DEV_CERTS = "1"
#SECURE_LINK_SERVER_HOST = "192.168.12.16"
#SECURE_LINK_SERVER_PORT = "6001"